### ISSUE TITLE
wrong offsets in side display after address 0xeeff

### ISSUE THREAD

**Issue by dennisbusch-de** [afrantzis/bless#1]
version number in about dialog: Bless 0.6.1

The offsets being displayed in the left side appear to be wrong after offset 0xeeff.
It reads eff00, should be ef00.

screenshot:
![20181128_100410_753574480](https://user-images.githubusercontent.com/11457085/49140664-2404be00-f2f5-11e8-9ef0-d5033f993f02.png)

**Comment by afrantzis** [comment]
Thanks for the report! I have pushed a fixed to master at 530845f.
