### ISSUE TITLE
Feature request: Copy byte offset

### ISSUE THREAD

**Issue by cweiske** [afrantzis/bless#15]
When taking notes during reverse engineering, I often need to copy relevant byte positions (offsets) to my notes.

It would be nice if I could right-click a byte and there was a "copy offset" context menu entry.

**Comment by afrantzis** [comment]
A useful feature indeed! 1296a73 adds support for copying the cursor offset or selection range offsets (if a selection is active). Available in the Edit menu, the right-click menu and also with the Ctrl+Shift+C shortcut. You can set the number base to use in the preferences. Enjoy!

**Comment by cweiske** [comment]
Thank you very much!
