### ISSUE TITLE
Compile issues on Ubuntu

### ISSUE THREAD

**Issue by plonibarploni** [afrantzis/bless#17]
I am experiencing issues trying to compile Bless on Ubuntu (19.10 development branch).
I did not install `scrollkeeper` (AFAIK it is not available in Ubuntu's repos), so it should - according to my understanding of the docs - *not* do any `scrollkeeper` related stuff. However, `make` is failing, and the output indicates that it's trying to do something with `scrollkeeper`.

Here's the relevant output from `make`:
```
Making all in user
make[2]: Entering directory '/home/dev/bless-0.6.2/doc/user'
if [ -x `which scrollkeeper-preinstall` ]; then \
    scrollkeeper-preinstall file:/usr/local/share/doc/bless/user/bless-manual.xml bless-manual.omf.in bless-manual.omf; \
else \
    cp bless-manual.omf.in bless-manual.omf; \
fi
/bin/bash: line 1: scrollkeeper-preinstall: command not found
make[2]: *** [Makefile:449: bless-manual.omf] Error 127
make[2]: Leaving directory '/home/dev/bless-0.6.2/doc/user'
make[1]: *** [Makefile:349: all-recursive] Error 1
make[1]: Leaving directory '/home/dev/bless-0.6.2/doc'
make: *** [Makefile:386: all-recursive] Error 1
```

I am using the 0.6.2 release tarball.

**Comment by plonibarploni** [comment]
If I remove the `if` statement it compiles and runs, but is affected by the same bug as #5.

**Comment by afrantzis** [comment]
Hi, this has already been fixed with https://github.com/afrantzis/bless/commit/e6d923235d6f22e8270df41e168227647ddfdce8 . Until the next release the solution is to use the latest git master.

**Comment by plonibarploni** [comment]
Do you have an ETA for the next release?

**Comment by plonibarploni** [comment]
I can confirm that commit fixes this issue (thank you for that!), and the standard `./autogen.sh && ./configure && make` works. However, I'm now having issues trying to package it as a `.deb`. Both `bzr builddeb` and `pbuilder-dist` fail with the following (admittedly unhelpful) error:
```
autoreconf: automake failed with exit status: 1
dh_autoreconf: autoreconf -f -i returned exit code 1
make: *** [debian/rules:18: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
```
