### ISSUE TITLE
Error building project: 'Range' is an ambiguous reference

### ISSUE THREAD

**Issue by davidcim** [afrantzis/bless#20]
"make" returns this error for 6 source files:
 > error CS0104: 'Range' is an ambiguous reference between 'System.Range' and 'Bless.Util.Range'

I have solved the issue editing the sources and explicitly choosing which I guess is the right class:
> using Range=Bless.Util.Range;

The files where the compiler complains are:
> src/buffers/ByteBuffer.cs
> src/gui/DataBookFinder.cs
> src/gui/areas/AreaGroup.cs
> src/tools/find/FindOperations.cs
> src/tools/find/IFindStrategy.cs
> src/tools/find/IFinder.cs

My mono version is:
> Mono JIT compiler version 6.4.0.198 (tarball Tue Sep 24 01:20:30 UTC 2019)

**Comment by davidcim** [comment]
Added a pull request with the fix.

**Comment by afrantzis** [comment]
Fixed by https://github.com/afrantzis/bless/commit/84801988f908e51d9843c3e0ee8f2cd05c0a2d97 .

**Comment by zahid2000** [comment]
👍👍👍
