### ISSUE TITLE
Missing monospace font markers

### ISSUE THREAD

**Issue by Erikvv** [afrantzis/bless#25]
![Screenshot_20191203_143448](https://user-images.githubusercontent.com/1748197/70055574-181f9c00-15da-11ea-9564-c0a0c57721d7.png)

Version: 0.6.2 installed from https://aur.archlinux.org/packages/bless/
Log:
```
$ bless PKGBUILD 
Could not find a part of the path '/home/erik/.config/bless/plugins'.
Could not find a part of the path '/home/erik/.config/bless/plugins'.
Could not find a part of the path '/home/erik/.config/bless/plugins'.
Could not find file "/home/erik/.config/bless/export_patterns"
```
I am running kde-plasma with no special configuration with regard to fonts. I do have several monospace fonts.

~~To solve it I tried changing the font as described [here](https://askubuntu.com/questions/110599/how-to-change-the-default-font-for-bless-hex-editor) but this makes no difference~~

**Comment by Erikvv** [comment]
I missed that it was compiled, I though it was a binary. I will check the build logs.

**Comment by afrantzis** [comment]
Hi! That's a strange issue... seems like pango (text engine library) is selecting a font that doesn't have basic glyphs. A few questions below to help us get to the bottom of this.

The default font is "Courier 12". Does the Courier font exist on your system? What does `fc-match Courier` output?

Also, when setting another font in the config file are you using the full name plus size (e.g., "Monospace 12")? Is the layout file you are changing actually used (check in Edit->Preferences->General->Default Layout)? What does `fc-match Monospace` output?

**Comment by afrantzis** [comment]
As an other test, how does the following layout look:

```xml
<layout>
    <area type="hexadecimal">
        <display>
            <font>Monospace 12</font>
        </display>
        <case>upper</case>
    </area>
</layout>
```
To use it, paste the above in `~/.config/bless/layouts/test.layout`, then enable it using the View->Layouts menu item.

**Comment by Erikvv** [comment]
```
$ fc-match Monospace
andalemo.ttf: "Andale Mono" "Regular"

$ fc-match Courier
pcrr8a.pfb: "Courier" "Regular"
```

With your layout `<font>Monospace 12</font>` things work:

![Screenshot_20191209_095231](https://user-images.githubusercontent.com/1748197/70421254-c3f93980-1a69-11ea-88a9-140e9fd56ede.png)

but with `<font>Courier 12</font>` it is placeholders again.

So the issue seems specific to that font on my system. It works in other applications though (intellij, browser, etc)

**Comment by afrantzis** [comment]
@Erikvv Hi! I was finally able to reproduce this error locally, and have committed a workaround in a46b8cc. I haven't been able to debug why this particular font (and apparently some other Type 1 fonts) have started failing, but hopefully this workaround will provide a better user experience.

**Comment by danielzgtg** [comment]
I found out why the fonts started failing.

["Pango stopped supporting old x11 fonts between versions 1.43 and 1.44, breaking them for all gtk apps."](https://askubuntu.com/a/1237020)

It seems that the problem in with this part of the stack because Bless, PyGTK, which all depend on Pango don't render Courier properly but Cairo, Mono, and Java do. Additionally, when temporarily downgrading from Ubuntu 20.04's Pango 1.44 to Ubuntu 19.10's Pango 1.42, the problem goes away.

> Courier works in other applications though (intellij, browser, etc)

It does indeed work in those applications. For the browser, both Chrome and Firefox work. However, none of them are pure GTK applications. GIMP and gedit, which use GTK for font rendering, don't work.

**Comment by fredericgermain** [comment]
It seems bless has this problem on Ubuntu 20.04.

Modifying `~/.config/bless/layouts/test.layout` didn't work.

But following this worked for me https://askubuntu.com/a/110625/284670

**Comment by Wohlstand** [comment]
Just now I made this:
[test.layout.gz](https://github.com/afrantzis/bless/files/5714275/test.layout.gz)
works on Linux Mint 20 (based on Ubuntu 20.04), paste it into `~/.config/bless/layouts/` directory. Then, you should choose it in settings:

![изображение](https://user-images.githubusercontent.com/6751442/102587415-d9914c80-411c-11eb-8e4c-bd1fe0c51206.png)

and voila!
![изображение](https://user-images.githubusercontent.com/6751442/102587471-edd54980-411c-11eb-9508-57d14118b0e7.png)
