### ISSUE TITLE
Reproducible crash when searching for specific byte sequence

### ISSUE THREAD

**Issue by kangalioo** [afrantzis/bless#3]
My system: `4.20.5-arch1-1-ARCH GNU/Linux`
Mono version: 5.16.0
GTK2 version: 2.24.32-1
GTK# version: 2.12.45-1
Steps to reproduce:

- Open any "Find" dialog box, with any document
- Type "0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 209 1" into it
- Select decimal, octal or binary as number base. Hexadecimal and text won't work
- Start the search

It does not matter what, or even if, a file was opened. Crash log: [pastebin link](https://pastebin.com/v51dB4Uk).

**Comment by afrantzis** [comment]
Thanks, fixed in master.
