### ISSUE TITLE
Characters not being displayed on Ubuntu 20.04

### ISSUE THREAD

**Issue by oriolarcas** [afrantzis/bless#30]
Hi,

Don't know if it's a Bless problem, but I don't see how to fix it and maybe somebody can help.

After upgrading from Ubuntu 18.04 to 20.04, Bless shows the numeric representation of characters, instead of the characters itself.

![bless](https://user-images.githubusercontent.com/5081071/86488186-71ae9b80-bd60-11ea-9e4b-630d28ea20c3.png)

Any file is shown like that. This only happens with the data view, the rest of the interface looks fine.

Usually the application crashes. Can provide call traces if needed.

**Comment by afrantzis** [comment]
Hi! This was reported in https://github.com/afrantzis/bless/issues/25. Please see the comments there for more information and various workarounds/solutions. Thanks!

**Comment by oriolarcas** [comment]
Thanks, my bad!

**Comment by oriolarcas** [comment]
For anyone having this problem their current Bless version, a workaround:

**1. Create this layout file:**

```
<layout>
    <area type="offset">
	<display>
	    <evenrow>
		<evencolumn>
		    <foreground>dark red</foreground>
		    <background>white</background>
		</evencolumn>
	    </evenrow>
	    <oddrow>
		<evencolumn>
		    <foreground>dark red</foreground>
		    <background>white</background>
		</evencolumn>
	    </oddrow>
	    <font>Monospace 12</font>
	</display>
    </area>
    
    <area type="separator">
    	<display>
	    <evenrow>
		<evencolumn>
		    <foreground>dark green</foreground>
		    <background>white</background>
		</evencolumn>
	    </evenrow>
	</display>

    </area>
    
    <area type="hexadecimal">
	<display>
	    <font>Monospace 12</font>
	</display>
	<case>upper</case>
    </area>

    <area type="separator">
	<display>
	    <evenrow>
		<evencolumn>
		    <foreground>dark green</foreground>
		    <background>white</background>
		</evencolumn>
	    </evenrow>
	</display>

    </area>
    
    <area type="ascii">
	<display>
	    <font>Monospace 12</font>
	</display>
    </area>
</layout>
```

**2. Save it into the directory:** `~/.config/bless/layouts` (create the directory if necessary)

Choose this layout from the menu `Edit > Peferences > Select Layout`.
