### ISSUE TITLE
No fonts?

### ISSUE THREAD

**Issue by misieck** [afrantzis/bless#36]
The edit window displays generic rectangles instead of characters. The address, the raw bytes and the textual form columns all show rectangles.
The UI - menus, tab title, tools, conversion table all display fonts properly. 
Tried the standard repo version in PopOs 20.04 as well as the flatpak (0.6.2) version.

**Comment by afrantzis** [comment]
Hi! This has been fixed in latest master, but isn't included in a release yet. Also see #25 which contains a workaround. Thanks!

**Comment by Wohlstand** [comment]
Is that the same issue? on Linux Mint 20 the same (on Mint 19.3 and older it works fine)
![Снимок экрана от 2020-12-18 10-25-04](https://user-images.githubusercontent.com/6751442/102586492-4e638700-411b-11eb-99d4-7bccb2379bb3.png)

**Comment by Wohlstand** [comment]
Okay, I copied the manual on how to fix this, composed by people.

1) download this file [test.layout.gz](https://github.com/afrantzis/bless/files/5714300/test.layout.gz) and unpack it
2) make the `~/.config/bless/layouts` directory
3) put the "test.layout" file into it
4) Open settings, and choose the pasted layout.
5) Voila!
![изображение](https://user-images.githubusercontent.com/6751442/102587790-810e7f00-411d-11eb-97fe-1fc7bc9940dc.png)
