### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by svenstaro** [afrantzis/bless#39]
Hey, I maintain bless in Arch Linux and I'd like to request a new official release of bless so that building becomes a bit less tedious.

**Comment by afrantzis** [comment]
Hi! I agree that a new release is in order. Hopefully I can get to it this week or early next week.

**Comment by afrantzis** [comment]
I have created a new v0.6.3 release: https://github.com/afrantzis/bless/releases/tag/v0.6.3

Thanks!
